### ISSUE TITLE
Re-enable in Stackage

### ISSUE THREAD

**Issue by pbrisbin** [soenkehahn/generics-eot#27]
:wave: Hi there-

It looks like this package is currently disabled in Stackage:

```yaml
    "Sönke Hahn <soenkehahn@gmail.com> @soenkehahn":
        - generics-eot < 0 # via interpolate
```

But we pull it in via `extra-deps` and it builds fine, even on nightly. Would it be OK if I re-enabled it as part of re-enabling our own packages that depend on it? I'm also happy to move it up into my own name's area if that's better for you.

**Comment by soenkehahn** [comment]
Thanks for reporting and sorry for the delay. Happy to re-enable the package on stackage. I've just opened this PR: https://github.com/commercialhaskell/stackage/pull/5898.

**Comment by soenkehahn** [comment]
It's back: https://www.stackage.org/nightly-2021-03-09/package/generics-eot-0.4.0.1
Thanks for reporting!

**Comment by pbrisbin** [comment]
Thank you!
